### ISSUE TITLE
Thanks for this repo. Not able to register to eureka.

### ISSUE THREAD

**Issue by prithwirajsinha** [xiaooloong/lua-resty-eureka-client#1]
Hi,

First of all, thanks for this repo.

This might be a very dumb issue as I am new to NGINX and lua.
So the issue is that I can talk to Eureka using this client as I can see it the logs but I can't register my app.

When I do this, I get Error Code: 401 - Unauthorized which is correct as I need to login.
`
 w:run({
        host = '127.0.0.1',
        port = 8761,
        uri  = '/eureka/apps',
        timeval = 30,
    }, i:export())
`
 
So, I put in the admin username and password like you would do in cURL like this 
`
 w:run({
        host = 'user:password@127.0.0.1',
        port = 8761,
        uri  = '/eureka/apps',
        timeval = 30,
    }, i:export())
`

And i get this in the logs - 

> no resolver defined to resolve "user", context: ngx.timer

I have tried using 'user:password@localhost' in a similar NPM Eureka client for a node js application and it works.
But it seems like either NGINX or this library doesn't support colons inside the **host** or follows a specific format for the **host**.

Any help would be appreciated!

Thanks.
Prithwiraj

**Comment by xiaooloong** [comment]
Thanks for using.
This eureka client is using `pintsized/lua-resty-http` to imitate HTTP requests, which is not support HTTP basic auth natively. I will try to add a `Authorization` header manually to fix this.

**Comment by prithwirajsinha** [comment]
It works!!!! Thank you so much!
